### ISSUE TITLE
Server doesn't allow e-mail address verification

### ISSUE THREAD

**Issue by misaon** [hbattat/verifyEmail#28]
Hi i have problem in your script if i verify specific email "fic@helbich.cz".

ERROR: Notice: fputs(): send of 4 bytes failed with errno=32 Broken pipe
in vendor/hbattat/verifyemail/src/VerifyEmail.php at line 151   -

```
$this->debug[] = 'Response: '.$to;
$this->debug[] = 'Sending QUIT...';
$quit = fputs ($this->connect , "QUIT");  <<--- problem here
$this->debug_raw['quit'] = $quit;
fclose($this->connect);
```

Can you make some exception?
My app now crashing.. :/
Thanks

**Comment by hbattat** [comment]
Hi,

This notice happens when the script is trying to write to a disconnected connection. if you look at the raw debug, you will see that the connection terminated by the server after the HELO command.

The fix is not to suppress the notice with "@" (as you suggested in your pull request) but rather figuring out the root cause.

Looking at https://www.ietf.org/rfc/rfc2821.txt and the syntax for HELO/EHLO it seems like I was providing the domain of the email we are trying to verify, which causes the mail server to thing this is a fraudulent request because the " mail from" value has a different domain.

Replacing the domain with the verifier domain solves the problem (see v1.0.7) but it looks like this server is like Yahoo it returns true for all values e.g. fic@helbich.cz is valid, anythinghere1212312@helbich.cz is also valid.

I hope this helps you.

Thanks
