### ISSUE TITLE
Not working for hotmail addresses

### ISSUE THREAD

**Issue by nobounces** [hbattat/verifyEmail#32]
All Hotmail addresses are returning as invalid.

**Comment by michaelsomerville** [comment]
So nobounces uses this script ? was going to use your site ... lol

**Comment by hbattat** [comment]
@michaelsomerville yes, pretty much their whole service is built on the top my script, but hey that's what open source is for.

This issue is only happening with their servers, they are blocked from Microsoft. My script has no issue if your server is not treated as a spam or malicious source.

@nobounces Please read the email I sent you last week and follow up on your part, I do have a solution for you, but need to get your action items done first :)

**Comment by redox63** [comment]
Hi hbattat,
Same problems with all microsoft address (live, hotmail, outlook). Do you have a solution for me too ;)
Bye

**Comment by SergiOnGit** [comment]
Hello @hbattat i have the same issue. Hotmail, live, outlook, yahoo, mail.ru, inbox.ru, list.ru none of them is checked correctly. It always says that mail exists but it's a false. Can you help me with this? I very very need it :)

**Comment by hbattat** [comment]
Now it works with all hotmail addresses. See v1.0.8
